controller_list:
  - name: ''
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_left_joint_s,
            arm_left_joint_l,
            arm_left_joint_e,
            arm_left_joint_u,
            arm_left_joint_r,
            arm_left_joint_b,
            arm_left_joint_t,
            arm_right_joint_s,
            arm_right_joint_l,
            arm_right_joint_e,
            arm_right_joint_u,
            arm_right_joint_r,
            arm_right_joint_b,
            arm_right_joint_t,
            torso_joint_b1]
  - name: sda20d/sda20d_r1_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_left_joint_s,
            arm_left_joint_l,
            arm_left_joint_e,
            arm_left_joint_u,
            arm_left_joint_r,
            arm_left_joint_b,
            arm_left_joint_t]
  - name: sda20d/sda20d_b1_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [torso_joint_b1]
  - name: sda20d/sda20d_r2_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_right_joint_s,
            arm_right_joint_l,
            arm_right_joint_e,
            arm_right_joint_u,
            arm_right_joint_r,
            arm_right_joint_b,
            arm_right_joint_t]
