controller_list:
  - name: fake_R1_controller
    joints:
      - arm_left_joint_s
      - arm_left_joint_l
      - arm_left_joint_e
      - arm_left_joint_u
      - arm_left_joint_r
      - arm_left_joint_b
      - arm_left_joint_t
  - name: fake_R2_controller
    joints:
      - arm_right_joint_s
      - arm_right_joint_l
      - arm_right_joint_e
      - arm_right_joint_u
      - arm_right_joint_r
      - arm_right_joint_b
      - arm_right_joint_t
  - name: fake_B1_controller
    joints:
      - torso_joint_b1
  - name: fake_R1R2_controller
    joints:
      - arm_left_joint_s
      - arm_left_joint_l
      - arm_left_joint_e
      - arm_left_joint_u
      - arm_left_joint_r
      - arm_left_joint_b
      - arm_left_joint_t
      - arm_right_joint_s
      - arm_right_joint_l
      - arm_right_joint_e
      - arm_right_joint_u
      - arm_right_joint_r
      - arm_right_joint_b
      - arm_right_joint_t
  - name: fake_R1B1_controller
    joints:
      - torso_joint_b1
      - arm_left_joint_s
      - arm_left_joint_l
      - arm_left_joint_e
      - arm_left_joint_u
      - arm_left_joint_r
      - arm_left_joint_b
      - arm_left_joint_t
  - name: fake_R2B1_controller
    joints:
      - torso_joint_b1
      - arm_right_joint_s
      - arm_right_joint_l
      - arm_right_joint_e
      - arm_right_joint_u
      - arm_right_joint_r
      - arm_right_joint_b
      - arm_right_joint_t
  - name: fake_R1R2B1_controller
    joints:
      - torso_joint_b1
      - arm_left_joint_s
      - arm_left_joint_l
      - arm_left_joint_e
      - arm_left_joint_u
      - arm_left_joint_r
      - arm_left_joint_b
      - arm_left_joint_t
      - arm_right_joint_s
      - arm_right_joint_l
      - arm_right_joint_e
      - arm_right_joint_u
      - arm_right_joint_r
      - arm_right_joint_b
      - arm_right_joint_t