# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_left_joint_b:
    has_velocity_limits: true
    max_velocity: 1.74
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_e:
    has_velocity_limits: true
    max_velocity: 1.039
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_l:
    has_velocity_limits: true
    max_velocity: 0.796
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_r:
    has_velocity_limits: true
    max_velocity: 1.5719
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_s:
    has_velocity_limits: true
    max_velocity: 0.9086
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_t:
    has_velocity_limits: true
    max_velocity: 2.0453
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_joint_u:
    has_velocity_limits: true
    max_velocity: 1.188
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_b:
    has_velocity_limits: true
    max_velocity: 1.74
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_e:
    has_velocity_limits: true
    max_velocity: 1.039
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_l:
    has_velocity_limits: true
    max_velocity: 0.796
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_r:
    has_velocity_limits: true
    max_velocity: 1.5719
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_s:
    has_velocity_limits: true
    max_velocity: 0.9086
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_t:
    has_velocity_limits: true
    max_velocity: 2.0453
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_joint_u:
    has_velocity_limits: true
    max_velocity: 1.188
    has_acceleration_limits: false
    max_acceleration: 0
  torso_joint_b1:
    has_velocity_limits: true
    max_velocity: 2.4434
    has_acceleration_limits: false
    max_acceleration: 0